/* live.js — Bridge between the bot and the static site.
 *
 * The bot writes an alert log (avisos.jsonl) and, optionally, a JSON dump
 * (api/live.json) with the latest alerts and the teams it follows. This script
 * reads that JSON and paints two areas of index.html:
 *
 *   1. #teams-strip  → team logo strip (if the JSON carries `equipos`)
 *   2. #feed         → "recent games" list, in the shape of the alert
 *
 * If the JSON is missing (static deploy without the bot) or empty, #feed shows a
 * neutral message and the page does not break. All painting is defensive: a
 * missing field never throws.
 *
 * The JSON is produced by `scripts/bridge_web.py` and shipped next to the site.
 * There are no calls to the Riot API from the browser: the site never exposes
 * the key and never does CORS to Riot.
 *
 * Text is English on purpose: the site is published in English, and the strings
 * here are the only copy that is not generated by `scripts/generar_web.py`. If a
 * second language is ever published, this file is one of the places that has to
 * change with it.
 */
(function () {
  "use strict";

  var RUTA = "api/live.json";
  var feed = document.getElementById("feed");
  var strip = document.getElementById("teams-strip");

  function el(tag, cls, html) {
    var n = document.createElement(tag);
    if (cls) n.className = cls;
    if (html != null) n.innerHTML = html;
    return n;
  }

  // "12s ago" / "4 min ago" / "3h ago" / "2d ago". Compact because it sits at
  // the foot of a card, where a full sentence would wrap.
  function tiempoRelativo(ts) {
    if (!ts) return "";
    var s = Math.floor(Date.now() / 1000 - ts);
    if (s < 60) return s + "s ago";
    if (s < 3600) return Math.floor(s / 60) + " min ago";
    if (s < 86400) return Math.floor(s / 3600) + "h ago";
    return Math.floor(s / 86400) + "d ago";
  }

  function pintarEquipos(equipos) {
    if (!strip || !equipos || !equipos.length) return;
    strip.innerHTML = "";
    equipos.slice(0, 24).forEach(function (eq) {
      var item = el("span", "team");
      if (eq.imagen) {
        var img = el("img");
        img.src = eq.imagen;
        img.alt = eq.nombre || eq.code || "";
        img.loading = "lazy";
        item.appendChild(img);
      }
      item.appendChild(document.createTextNode(eq.code || eq.nombre || ""));
      strip.appendChild(item);
    });
  }

  function pintarFeed(avisos) {
    if (!feed) return;
    if (!avisos || !avisos.length) {
      feed.innerHTML =
        '<div class="vacio">No alerts recorded on this deploy yet. ' +
        "When a pro queues up for SoloQ, the alert shows up here in real time.</div>";
      return;
    }
    feed.innerHTML = "";
    avisos.slice(0, 12).forEach(function (a) {
      var card = el("div", "card");
      var head =
        '<div class="ico">🎯</div><h3>' +
        escapeHtml(a.jugador || "Player") +
        (a.equipo
          ? ' <span class="quien-equipo">· ' + escapeHtml(a.equipo) + "</span>"
          : "") +
        "</h3>";
      var lineas = [];
      if (a.liga) lineas.push("<b>League:</b> " + escapeHtml(a.liga.toUpperCase()));
      if (a.campeon) lineas.push("<b>Champion:</b> " + escapeHtml(a.campeon));
      if (a.rango) lineas.push("<b>Rank:</b> " + escapeHtml(a.rango));
      if (a.servidor) lineas.push("<b>Server:</b> " + escapeHtml(a.servidor));
      var pie = '<p class="cuando">' + tiempoRelativo(a.ts) + "</p>";
      card.innerHTML = head + "<p>" + lineas.join("<br>") + "</p>" + pie;
      feed.appendChild(card);
    });
  }

  function escapeHtml(s) {
    return String(s == null ? "" : s)
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;");
  }

  fetch(RUTA, { cache: "no-store" })
    .then(function (r) {
      if (!r.ok) throw new Error("HTTP " + r.status);
      return r.json();
    })
    .then(function (data) {
      pintarEquipos(data.equipos);
      pintarFeed(data.avisos);
    })
    .catch(function () {
      // Silent: the static site works without the bot.
      if (feed) {
        feed.innerHTML =
          '<div class="vacio">Live data is not available on this deploy. ' +
          "The alert is posted to Discord the moment a pro enters a game.</div>";
      }
    });
})();
